version: '3.7'

services:
  coderr.communityserver:
    image: coderrio/communityserver-win
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - coderr_network_win

volumes:
  esdata:
    driver: local

networks:
  coderr_network_win:
    name: coderr_network_win



